CREATE TABLE DEPARTMENTS (
          Dept_ID INT PRIMARY KEY,
          Dept_Name VARCHAR(100) )

CREATE TABLE EMPLOYEEE (
          Emp_ID INT PRIMARY KEY,
          Emp_Name VARCHAR(50),
          Salary DECIMAL(10,2),
          Dept_ID INT ,
          FOREIGN KEY (Dept_ID) REFERENCES DEPARTMENT(Dept_ID) )

INSERT INTO DEPARTMENTS VALUES( 5,'MECH')

INSERT INTO EMPLOYEEE VALUES( 5,'ajith',620000.00,2)



SELECT * FROM DEPARTMENTS
SELECT * FROM EMPLOYEEE

SELECT Emp_Name,Dept_ID,CASE 
    WHEN Salary >= 100000.00 THEN 'HIGH'
    WHEN Salary BETWEEN 59000.01 AND 99999.99 THEN 'MEDIUM'
    WHEN Salary = 50000.00 THEN 'GOOD'
    WHEN Salary < 50000.00 THEN 'LOW'
  END AS CATEGORY
FROM EMPLOYEEE;

SELECT MAX(Salary) AS MAXIMUM FROM EMPLOYEEE

ALTER TABLE EMPLOYEEE
ADD DOJ DATE

SELECT * FROM EMPLOYEEE
WHERE Salary < ( SELECT AVG(Salary) FROM EMPLOYEEE)

SELECT * FROM EMPLOYEEE
ORDER BY Salary DESC 


